universe = vanilla

# The script to run
executable = train_multi_attack.sh


# setup checkpointing
checkpoint_exit_code = 85
transfer_checkpoint_files = adv_train_outputs/
+is_resumable = true


# Condor log/output files
log     = logs/job_$(Cluster)_$(Process).log
output  = logs/job_$(Cluster)_$(Process).out
error   = logs/job_$(Cluster)_$(Process).err

environment = WANDB_API_KEY=2f6472720d0bcd23e9b32b6cde8216db88dc5453


# Transfer your code and packed env
should_transfer_files = YES
transfer_input_files = textattack_env.tar.gz, test_noiser_train.py, train_multi_attack.sh
when_to_transfer_output   = ON_EXIT_OR_EVICT
transfer_output_files     = adv_train_outputs, wandb, logs
when_to_transfer_output = ON_EXIT

# treat our checkpoint exit as a hold for auto-retry
on_exit_hold              = (ExitCode == 85) || (ExitSignal == 15) || (ExitSignal == 9)
periodic_release          = (NumJobStarts < 20)


# define gpu lab parameters
+WantGPULab = true
+GPUJobLength = "long"
gpu_minimum_capability = 8.0

# Resource requests
request_cpus    = 4
request_memory  = 32GB
request_disk    = 32GB
request_gpus  = 4

queue 1